sources=pcre_byte_order.c \
        pcre_chartables.c \
        pcre_compile.c \
        pcre_config.c \
        pcre_dfa_exec.c \
        pcre_exec.c \
        pcre_fullinfo.c \
        pcre_get.c \
        pcre_globals.c \
        pcre_jit_compile.c \
        pcre_maketables.c \
        pcre_newline.c \
        pcre_ord2utf8.c \
        pcre_refcount.c \
        pcre_study.c \
        pcre_tables.c \
        pcre_ucd.c \
        pcre_valid_utf8.c \
        pcre_version.c \
        pcre_xclass.c
objects=$(sources:.c=.obj)
target_dir=..\lib
target=$(target_dir)\pcre.lib

!include ..\build\msvc.inc

DEFINES=$(DEFINES) /DHAVE_CONFIG_H

all:
	$(mkoutdir)
	$(CC) $(CFLAGS) $(DEFINES) $(sources) $(INCLUDES)
	$(AR) $(ARFLAGS) /OUT:"$(target)" $(objects)

clean:
	$(RM) $(objects)

distclean: clean
	$(RM) "$(target)"
